name: Deploy to Netlify

on:
  push:
    branches:
      - main # Deploy on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install # Use "npm ci" if you have a lock file

    - name: Build website
      run: npm run build # Adjust according to your build command

    - name: Deploy to Netlify
      uses: netlify/actions/deploy@v2
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
